# Generated by Django 5.2.5 on 2025-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
